### ISSUE TITLE
pv live consumer app

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/pvoutput#90]
## Detailed Description
- Create entry point that loads the most recent pv data from all the sites in the UK and saves them to a database
- option for different company
- option for what DB_URL to save to

The tasks it should do
1. Create a list of UK grid points - [notebook](https://github.com/openclimatefix/pvoutput/blob/main/examples/compute_grid_points_for_UK.ipynb), or use `from pvoutput.grid_search import GridSearch`
2. Get PV systems by looping over grid points - [notebook](https://github.com/openclimatefix/pvoutput/blob/main/examples/query_API_for_all_UK_grid_points.ipynb), or [notebook](https://github.com/openclimatefix/pvoutput/blob/main/examples/get_all_systems_in_region.ipynb)
3. Save PV systems in database, if not there already
4. Get status for each pv system right now 
5. save to database

Need to check if we need to get full metadata of the system

## Context
Good to save PV data, so we it can be used in ML models to predict solar generation

**Comment by peterdudfield** [comment]
@JackKelly I think you've had the most experience with this code, do you think the steps above are sensible? Anything missing

**Comment by JackKelly** [comment]
I must admit it's been literally about two years since I looked at this code so my memory will be rusty!

A few quick thoughts:

At inference time, our ML models will probably only be able to consume PV data from PV systems that the model has seen during training. Also, only about half the PV systems from PVOutput.org actually have valid power data.

So I wouldn't bother with steps 1 and 2 above. Instead, I'd recommend that we maintain a list of "PV system IDs" that we want data from at inference time. This list would probably be created during training. For the MVP, we could just use the list of PV system IDs in the PVOutput.org data that we used during training last year.

I'd maybe recommend a workflow something like this:

1. Read the list of "PV system IDs" and read their update frequency (some PV systems are updated every 5 minutes; some every 15 minutes; some every hour. The update frequency is in the PVOutput.org metadata).
2. For each PV system ID:
    1. Check our local database to find out the time of the most recent PV data for that PV system ID. (Also handle the case when there is no data in our local database for the PV system ID yet.)
    2. If `(now - time_of_most_recent_data_in_ocf_database) >= update_period_for_pv_system` then query PVOutput.org for data for `pv_system_id` between `time_of_most_recent_data_in_ocf_database` and now.
    3. Save that data (in chronological order) into our DB. It's important to save in chronological order so if the saving fails half-way-through, the `time_of_most_recent_data_in_ocf_database` will be correct.
    
This way, the script should "do the right thing" if the script dies part way through; or if a handful of PV systems don't update for a while; or if we add new PV system IDs to the list.

**Comment by peterdudfield** [comment]
Thanks @JackKelly for this

I'd create a list of PV systems that we can use - Thats keep things simple for the MVP. 

In ii) Would it be a time series of power, or just one power value. I imagine it would be a timeseries. 

iii) thats not a problem, with sql database, we can order by a column, for example datetime. Also `sqlalchemy` handles lots of things about it failing halfway through. 

So just to re write it in my own words
1. Read list of PV systems (from local file) and get their refresh times (refresh times can also be stored locally)
2. Find most recent entered data (for each PV system) in OCF database
3. Pull data, if more data is available. This can be done by checking the refresh rate. (for each PV system) 
4. Save to database - perhaps check no duplicate data. (for each PV system)

**Comment by JackKelly** [comment]
Sounds good to me!

> In ii) Would it be a time series of power, or just one power value

Yeah, I think `pvoutput.org` provides a `batch_status` query (or something like that!) which allows you to get a whole timeseries for a single PV system, and I think you can specify the date range for the query.

**Comment by peterdudfield** [comment]
I'm tempted to put this 'live' code in a separate repo. I like the idea that we have
- pvoutput repo: good for python wrapper around pvoutput api. This can be used by the wider community.
- PVConsumer: This would be specific to OCF. Runs an application to pull live data, interactions with datamodel. It would install the pvoutput as a library. This could exapnd to import other librarys, i.e pull other PV data sources.

What do you think @JackKelly, @jacobbieker?

**Comment by peterdudfield** [comment]
Im gona give it a go here - https://github.com/openclimatefix/PVConsumer
